name: Deploy website to S3 and invalidate CloudFront

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create config.js from secret
        run: |
          echo "export const APIURL = '${{ secrets.APIURL }}';" > frontend/script/config.js

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::861276104231:role/github-actions-role
          aws-region: eu-central-1

      - name: Deploy to S3
        run: aws s3 sync ./frontend/ s3://mycrcstaticwebsite --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/*"
